name: campus-nav-prod

services:
  emulator:
    build:
      context: .
      dockerfile: firebase.Dockerfile
    ports:
      - "9099:9099"
      - "8080:8080"

  web:
    build:
      context: .
      target: runner
      args:
        NEXT_PUBLIC_FIREBASE_USE_EMULATOR: "true"
        NEXT_PUBLIC_FIREBASE_API_KEY: demo-key
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: demo-campus
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: demo-campus.firebaseapp.com
    ports:
      - "3000:3000"
    depends_on:
      - emulator
